### ISSUE TITLE
Remove cache warning

### ISSUE THREAD

**Issue by felixwellen** [felixwellen/synthetic-zariski#21]
I'm planning to remove this warning:

![image](https://github.com/felixwellen/synthetic-zariski/assets/22154668/d57bfa8a-1271-49b7-9f64-f6e02195cf2e)

I don't remember what problem made me put it everywhere (I think there was one though). Comment here if you think the warning should stay.

**Comment by mnieper** [comment]
+1

Put it just once in the top-level README.

Am So., 3. März 2024 um 12:13 Uhr schrieb Felix Cherubini <
***@***.***>:

**Comment by felixwellen** [comment]
Right! :-)
