### ISSUE TITLE
CITATION.cff

### ISSUE THREAD

**Issue by mnieper** [felixwellen/synthetic-zariski#22]
Shall we make this repo BibTex-aware?

https://citation-file-format.github.io/

**Comment by xuanruiqi** [comment]
Sounds like a good idea to me!

**Comment by felixwellen** [comment]
It seems to me that CITATION.cff is for a whole *repository*. So far I only wanted to cite specific drafts from this repository. Would a CITATION.cff help with that? Or is there a reasonable situation where you want to cite the whole repository?

**Comment by mnieper** [comment]
Yes, I mean the whole repository when the general work on synthetic algebraic geometry is to be cited. (I don't know of a GitHub-way to generator BibTeX entries for individual files.)

**Comment by felixwellen** [comment]
Something like #24
