### ISSUE TITLE
Basic opens of the affine parts...

### ISSUE THREAD

**Issue by mnieper** [felixwellen/synthetic-zariski#23]
In Proposition 5.1.3 in the Foundations, it says 

> basic opens of the affine parts of $X$

where $X$ is a scheme. As the datum of an affine cover of $X$ is truncated to a mere proposition in the definition of a scheme, "basic opens of the" seems superfluous, doesn't it?

**Comment by felixwellen** [comment]
Yes, it should just be an open affine cover - I guess we could only say more for special schemes.

**Comment by felixwellen** [comment]
pushed -> closing (feel free to reopen if you disagree with what I said..).
