### ISSUE TITLE
Quasi-projective schemes are A1-equivalent to affine schemes

### ISSUE THREAD

**Issue by felixwellen** [felixwellen/synthetic-zariski#9]
Peter Arndt suggested the following classic trick:

There is a map to $\mathbb{P}^n$, from the affine type of matrices $A:R^{(n+1)\times (n+1)}$ such that $A^2=A$ and the characteristic polynomial of $A$ is $X(X-1)$. Then, for example, the fiber over $[(1,0,\dots,0)]:\mathbb{P}^n$ consists of all matrices  where the first line is $(1 ~ a_0 \dots a_n)$ and everything else $0$.

The conditions are closed so this type of matrices is affine and all fibers of the map to  $\mathbb{P}^n$ are $\mathbb{A}^1$-connected.
The latter implies this map is an $\mathbb{A}^1$-equivalence.

This extends to closed subsets of  $\mathbb{P}^n$ by pullback.

For an open subset $U$ of a closed $V\subseteq \mathbb{P}^n$ (i.e. a quasi-projective scheme), we first take a closed complement $Z$ of $U$. $Z$ is also a closed subset of $\mathbb{P}^n$. So we can take the blow-up $B$ of $\mathbb{P}^n$ at $Z$, which is projective again and therefore has a map from an affine type with $\mathbb{A}^1$-connected fibers.

Let $\widetilde{U}$ be the preimage of $U$ in $B$, then the projection $\widetilde{U}\to U$ has  $\mathbb{A}^1$-connected fibers. $\widetilde{U}$ is affine, by Serre-Affinity and #10, since it is an locally-standard open (due to properties of the blow-up).

**Comment by hmoeneclaey** [comment]
I've added notes toward this to $\A^1$-homotopy under the name of Jouanolou's trick. I did not treat the case of open in projective. The characteristic polynomial of $A$ should be $X^n(X-1)$ (rather than $X(X-1)$) so that $A$ is a projection of rank $1$.

**Comment by hmoeneclaey** [comment]
I have finished the notes about Jouanolou's trick. The proof I propose is a bit simpler in the sense that it does not use blow up.

**Comment by felixwellen** [comment]
As stated above, this is written down now -> closing.
